//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BZ.INZ.Integration.SomeExternalSystem.ExternalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExternalService.IHelloService")]
    public interface IHelloService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/ExtarnalSystemFunction", ReplyAction="http://tempuri.org/IHelloService/ExtarnalSystemFunctionResponse")]
        string ExtarnalSystemFunction(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/ExtarnalSystemFunction", ReplyAction="http://tempuri.org/IHelloService/ExtarnalSystemFunctionResponse")]
        System.Threading.Tasks.Task<string> ExtarnalSystemFunctionAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloServiceChannel : BZ.INZ.Integration.SomeExternalSystem.ExternalService.IHelloService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloServiceClient : System.ServiceModel.ClientBase<BZ.INZ.Integration.SomeExternalSystem.ExternalService.IHelloService>, BZ.INZ.Integration.SomeExternalSystem.ExternalService.IHelloService {
        
        public HelloServiceClient() {
        }
        
        public HelloServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ExtarnalSystemFunction(string data) {
            return base.Channel.ExtarnalSystemFunction(data);
        }
        
        public System.Threading.Tasks.Task<string> ExtarnalSystemFunctionAsync(string data) {
            return base.Channel.ExtarnalSystemFunctionAsync(data);
        }
    }
}
